 bind_addr = ":8080"
 log_level = "debug"
 database_url = "host=localhost dbname=restapi_dev user=postgres password=postgres sslmode=disable"
 session_key = "4892j4923h4h9185772-g857-n4328vn57432nv57n43v57n437v5n84235nv8945n8v7v5"